version: '3.8'
services:
  mysql:
    image: mysql:9.2
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: wederm_mall
      MYSQL_USER: root
      MYSQL_PASSWORD: 

    volumes:
    - ./init:/docker-entrypoint-initdb.d



  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/wederm_mall
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
    
    ports:
      - 9090:9090
    depends_on:
      - mysql
    

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
