version: '3.8'
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: wederm8658jeb
      MYSQL_DATABASE: organica
      MYSQL_USER: wedermJEB
      MYSQL_PASSWORD: wederm8658jeb

    volumes:
    - ./init:/docker-entrypoint-initdb.d



  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/organica
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    
    ports:
      - 9090:9090
    depends_on:
      - mysql
    

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
